# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggI5YyvSW_G3oyLnFq2O7woYigtE9dDz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Write a program to find whether a given year is a leap year"""

year = int(input("Enter the year: "))

if (year%4 == 0 and year%100 != 0) or year%400 == 0:
   print(f'The year {year} is a leap year')
else:
   print(f'The year {year} is not a leap year')

"""Check whether a string is a palindrome."""

stri = input('Enter a string: ')
rev = stri[::-1]

if stri==rev:
    print('This is a palindrome')
else:
    print('This is not a palindrome')

"""Find the Fibonacci Series of a given number"""

n = int(input('Enter the number of elements: '))
li = [0,1]


for i in range(n-2):
    temp = li[i] + li[i+1]
    li.append(temp)

print(li)

"""Check whether a given number is a prime number or not"""

def primecheck(n):
    if n<=1:
        return False

    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False

    return True

num = int(input('Enter an integer: '))
val = primecheck(num)

if val:
    print(f'The number {num} is a prime number')
else:
    print(f"The number {num} is not a prime number")

"""Write a function to determine the number of vowels in a string"""

def count(str):
    vowel = 'aeiou'
    tc = 0

    for char in str:
        if char in vowel:
            tc+=1

    return tc

string = input("Enter a string: ").lower().strip()
c = count(string)
print(f"The number of vowels in {string}: {c}")

"""Assignment 2:

Write a program to remove duplicate values from a list and display only unique elements.
"""

el = [10,20,30,20,10,50,30,20]
s = set(el)
print("unique elements: ",list(s))

"""Write a program to sort a list in ascending and descending order."""

n = int(input('Enter number of elements: '))
li = []
for i in range(n):
    el = int(input('Enter elements: '))
    li.append(el)

li.sort()
print(f"The list in ascending: ",li)

li.sort(reverse=True)
print(f"The list in descending: ",li)

"""Write a program to create a dictionary of student marks, add a new student, update marks, and find the student with the highest marks."""

data = {'A':80, 'B':67, 'C':90, 'D':87, 'E':98}
data['F'] = 66   # add new student
data['B'] = 70   #update existing data

print(data)
maxstd = max(data, key=data.get)
print(f'The top scorer is student {maxstd} with score: {data[maxstd]}')

"""Write a program to count how many times each element appears in a list."""

n = int(input('Enter the number of elements: '))
li = []

for i in range(n):
    el = int(input('Enter the elements: '))
    li.append(el)

count = {}
for key in li:
    if key in count:
        count[key] += 1
    else:
        count[key] = 1

print(f"Total number of frequency: {count}")

"""Write a program to count the frequency of each word in a sentence and display unique words."""

str = input('Enter the sentence: ')
word = str.split()

count = {}
for w in word:
    if w in count:
        count[w] += 1
    else:
        count[w] = 1
word = set(word)
print(f'The unique words: {word}')
print(f'The number of unique words: {count}')

"""Removing negative values using filtering condition"""

temp = [100,150,380,-200,290,-100]

upd = [x for x in temp if x>0]
print(f'Original list: {temp}')
print(f"List without negative values: {upd}")

"""You are given a raw stream of sales data. Each entry is a tuple containing (Transaction_ID,
Product_Name, Category, Price).
Your Tasks:
I. Deduplication: Remove duplicate transactions based on Transaction_ID.
II. Cataloging: Create a Dictionary where keys are Categories and values are Sets of
unique products in that category.
III. Revenue Tracking: Calculate the total revenue per product using a Dictionary.
IV. Performance: Identify the most expensive product in each category.
"""

items = [
    (101, "Laptop", "Electronics", 50000),
    (102, "Monitor", "Electronics", 30000),
    (103, "Chair", "Furniture", 10000),
    (104, "Table", "Furniture", 12000),
    (101, "Laptop", "Electronics", 50000),
    (103, "Chair", "Furniture", 10000),
    (106, "Lamp", "Equipment", 5000)
]

#1
uniItems = {}
catItems = {}
revenue = {}
MaxPriceperCat = {}

for tid, prod, cat, pr in items:
    if tid not in uniItems:
        uniItems[tid] = (prod, cat, pr)
print(f"Unique items based on ID: {uniItems}")

#2

for prod, cat, pr in uniItems.values():
    if cat not in catItems:
        catItems[cat] = set()
    catItems[cat].add(prod)

#3
for tid, prod, cat, pr in items:
    if prod in revenue:
        revenue[prod] += pr
    else:
        revenue[prod] = pr

#4
for prod, cat, pr in uniItems.values():
    if cat not in MaxPriceperCat or pr > MaxPriceperCat[cat][1]:
        MaxPriceperCat[cat] = (prod, pr)

print(f"\nUnique category based products: {catItems}\n")
print(f"The total revenue per product: {revenue}\n")
print(f"Maximum price of product per category: {MaxPriceperCat}")

"""You are given a list of log entries where each entry is a Tuple: (Timestamp, IP_Address,
Status_Code).
Requirements:
I. Deduplicate: Remove identical log entries (some servers send the same log twice).
II. Filter: Only keep entries with "Error" status codes (400-599).
III. Group: Create a Dictionary where the key is the IP_Address and the value is a List
of timestamps associated with that IP's errors.
IV. Unique Attackers: Identify the total number of unique IP addresses that caused
errors using a Set.
"""

logs = [
    ("10:00:01", "192.168.1.1", 200),
    ("10:00:02", "192.168.1.5", 404),
    ("10:00:02", "192.168.1.5", 404),
    ("10:00:03", "192.168.1.1", 500),
    ("10:00:04", "172.16.0.45", 403),
    ("10:00:05", "192.168.1.1", 200),
    ("10:00:06", "172.16.0.45", 403)
]

#1
uniLogs = set(logs)

#2
error = []
for time, ip, stat in uniLogs:
    if stat > 399 and stat < 600:
        error.append((time, ip, stat))

#3
logdict = {}
for time, ip, stat in error:
    if ip not in logdict:
        logdict[ip] = []
    logdict[ip].append(time)

#4
uniAttacker = set(logdict.keys())
numofAttack = len(uniAttacker)

print(f'Unique log entries: {uniLogs}')
print(f'\nErrors with status codes(400-599): {error}')
print(f'\nUnique IP addresses attacks from: {logdict}')
print(f'\nNumber of unique IP addresses: {numofAttack}')

"""You are given a list of academic records. Each record is a Tuple in the format:
(Department, Student_Name, Subject, Score).
Because the data comes from different faculty databases, there are duplicate entries that
need to be cleared. Your goal is to process this data to provide a summary of scores grouped
by department.
Requirements:
I. Deduplicate: Remove any identical records using a Set.
II. Group: Use a defaultdict to group all scores (integers) under their respective
Department keys.
III. Aggregate: Create a final Dictionary where the key is the Department and the value
is a Tuple containing:
a. The total number of unique students in that department.
b. The average score of the department.
IV. Order: Ensure the final output is printed in alphabetical order of the departments.
"""

from collections import defaultdict

record = [
    ("CS", "Alice", "Python", 90),
    ("Math", "Bob", "Calculus", 80),
    ("CS", "Alice", "Python", 90),
    ("CS", "Charlie", "C++", 70),
    ("Math", "Bob", "Algebra", 70),
    ("Physics", "David", "Optics", 85),
    ("CS", "Alice", "Algorithms", 95)
]

#1
uniRecords = set(record)

#2
deptScore = defaultdict(list)
deptStd = defaultdict(set)

for dept, name, sub, score in uniRecords:
    deptScore[dept].append(score)
    deptStd[dept].add(name)

#3
finaldict = {}

for dept in deptScore:
    avgScore = sum(deptScore[dept])/len(deptScore[dept])
    totalStd = len(deptStd[dept])
    finaldict[dept] = (totalStd, avgScore)

#4
print(f'Unique records of students: {uniRecords}\n')
print('Department  Unique Student  Average Score\n')

for dept in sorted(finaldict.keys()):
    std, avg = finaldict[dept]
    print(f'{dept}\t\t{std}\t\t{avg}\n')

"""Assignment 3: Matplotlib

Line Plot: Create a line chart showing monthly sales. Add title, labels, grid, markers, and explain the
sales trend.
"""

month = ['January', 'February', 'March', 'April', 'May', 'June', 'July']
sales = [200, 150,450,360,230,260,400]

plt.plot(month,sales, linestyle='-', marker = 'o', label='Sales')
plt.title('Sales projection on monthly basis')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.grid(True)
plt.legend()
plt.show()

"""Multiple Line Plot: Compare two students' performances across subjects using different line styles and a
legend. Interpret the results. Use different line styles and markers. Add a legend. Add a suitable title.
"""

subject = ['Math', 'Science', 'ICT', 'Bengali', 'English']
s1 = [87,67,90,77,89]
s2 = [76,69,39,58,92]
length = np.arange(len(subject))

plt.plot(length, s1, color="green", linestyle='-', marker='o',label='student 1')
plt.plot(length, s2, color="red", linestyle='-.', marker='s',label='student 2')
plt.xlabel('Subjects')
plt.ylabel('Students marks')
plt.xticks(length,subject,rotation=55)
plt.title('Two students marks analysis')
plt.legend()
plt.show()

"""Bar Chart: Visualize student enrollment in departments. Display values above bars and discuss which
department has the highest enrollment. Add different colors.
and display values on top of each bar.
"""

dept = ['CSE', 'Pharmacy', 'Physics', 'Chemistry', 'Geography']
student = [50,60,170,200,100]
length = np.arange(len(dept))
col = ['red', 'blue', 'green', 'grey', 'orange']

bar = plt.bar(length, student, color= col)

for b in bar:
    height = b.get_height()
    plt.text(b.get_x(), height+3, str(height))

plt.title('Student enrollment across departments')
plt.xlabel('Department')
plt.ylabel('Number of students')
plt.xticks(length, dept, rotation=45)
plt.show()

"""Histogram: Plot marks distribution. Choose appropriate bins and explain whether the data is
symmetric, skewed, or clustered. Use appropriate bins. Add title and axis labels. Explain the distribution of marks.
"""

marks = [70,69,50,60,80,89,58,59,68,77,67,60,57,59,88,98,84,58,68]

plt.hist(marks, bins=7, color='orange', edgecolor='green')
plt.title('Marks Distribution')
plt.xlabel('Marks')
plt.ylabel('No of students')
plt.show()

"""Show daily activity distribution. Display percentages and highlight the largest segment.
activities = ["Study", "Sleep", "Exercise", "Entertainment", "Others"]
hours = [6, 8, 1, 4, 5]
Requirements: Display percentages. Highlight the largest segment. Add a title.
"""

activity = ['Study', 'Sleep', 'Exercise', 'Entertainment', 'Others']
hours = [6,8,1,4,5]

explode = [0, 0.1, 0,0,0]
plt.pie(hours, labels=activity,autopct = '%1.1f%%', explode=explode)
plt.title('Daily activity distribution')
plt.show()

"""Graph all this in subplots"""

fig, ax = plt.subplots(2,2, figsize=(12,8), constrained_layout=True)

subject = ['Math', 'Science', 'ICT', 'Bengali', 'English']
s1 = [87,67,90,77,89]
s2 = [76,69,39,58,92]
length = np.arange(len(subject))

ax[0,0].plot(length, s1, color="green", linestyle='-', marker='o',label='student 1')
ax[0,0].plot(length, s2, color="red", linestyle='-.', marker='s',label='student 2')
ax[0,0].set_xlabel('Subjects')
ax[0,0].set_ylabel('Students marks')
# ax[0,0].set_xticks(length,subject,rotation=55)
ax[0,0].set_title('Two students marks analysis')
ax[0,0].legend()




dept = ['CSE', 'Pharmacy', 'Physics', 'Chemistry', 'Geography']
student = [50,60,170,200,100]
length = np.arange(len(dept))
col = ['red', 'blue', 'green', 'grey', 'orange']

bar = ax[0,1].bar(length, student, color= col)

for b in bar:
    height = b.get_height()
    plt.text(b.get_x(), height+3, f'{height}')

ax[0,1].set_title('Student enrollment across departments')
ax[0,1].set_xlabel('Department')
ax[0,1].set_ylabel('Number of students')
# ax[0,1].set_xticks(length, dept, rotation=45)



marks = [70,69,50,60,80,89,58,59,68,77,67,60,57,59,88,98,84,58,68]

ax[1,0].hist(marks, bins=7, color='orange', edgecolor='green')
ax[1,0].set_title('Marks Distribution')
ax[1,0].set_xlabel('Marks')
ax[1,0].set_ylabel('No of students')



activity = ['Study', 'Sleep', 'Exercise', 'Entertainment', 'Others']
hours = [6,8,1,4,5]

explode = [0, 0.1, 0,0,0]
ax[1,1].pie(hours, labels=activity,autopct = '%1.1f%%', explode=explode)
ax[1,1].set_title('Daily activity distribution')

plt.tight_layout()
plt.show()

"""Assignment 4: Numpy

Analyze student performance across different subjects using numpy arrays
"""

student = ['s1', 's2', 's3', 's4']
subject = ['Math', 'Science', 'English']
mark = np.array([
    [70,80,65],
    [85,65,83],
    [78,98,47],
    [65,59,60]
])

print('Sum of total marks by student: ',np.sum(mark, axis=1))
print('Mean of all marks by students: ',np.mean(mark, axis=1))
print('Maximum mark achieved by subject: ',np.max(mark, axis=0))
print('Minimum mark achieved by subject: ',np.min(mark, axis=0))
print('Maximum mark achieved by student: ',np.max(mark, axis=1))
print('Minimum mark achieved by student: ',np.min(mark, axis=1))

topmarks = np.sum(mark, axis=1)
topper = np.argmax(topmarks)
print('The top scorer: ',student[topper])

"""Calculate averages, identify highest marks, and filter students based on conditions. (Using the previous dataset)"""

student_avg = np.mean(mark, axis=1)
print("Student-wise Average:", student_avg)

subject_avg = np.mean(mark, axis=0)
print("Subject-wise Average:", subject_avg)

student_total = np.sum(mark, axis=1)
print('Student wise total: ', student_total)

print("\nHighest Mark:", np.max(mark))
print("Student-wise Highest Marks:", np.max(mark, axis=1))
print("Subject-wise Highest Marks:", np.max(mark, axis=0))

excellent = np.array(student)[student_avg >= 80]
print("\nStudents who got A+ on avg:", excellent)

failed = np.array(student)[np.any(mark < 60, axis=1)]
print("Students who got poor result:", failed)

#students ranking
rank_indices = np.argsort(student_total)[::-1]
print("\nStudent Ranking:")
for i, idx in enumerate(rank_indices):
    rank = i + 1
    if rank == 1:
        suffix = "st"
    elif rank == 2:
        suffix = "nd"
    elif rank == 3:
        suffix = "rd"
    else:
        suffix = "th"
    print(f"{rank}{suffix} Place: {student[idx]} (Total: {student_total[idx]})")

print()
# student grades
grades = []
for a in student_avg:
    if a >= 80:
        grades.append("A+")
    elif a >= 70:
        grades.append("A")
    elif a >= 60:
        grades.append("B")
    elif a >= 50:
        grades.append("C")
    else:
        grades.append("F")
grades = np.array(grades)

for i in range(len(student)):
    print(student[i], "->", "Avg:", round(student_avg[i], 2), "Grade:", grades[i])

"""Assignment 5"""

import sys

class Account:
    """Represents a customer's individual bank account."""
    def __init__(self, account_number, pin, account_holder, initial_balance=0.0):
        self.account_number = account_number
        self.__pin = pin  # Encapsulation: Private variable to secure the PIN
        self.account_holder = account_holder
        self.__balance = initial_balance  # Encapsulation: Protected balance access

    def verify_pin(self, entered_pin):
        """Verifies if the entered PIN matches the account PIN securely."""
        return self.__pin == entered_pin

    def get_balance(self):
        """Getter method to securely check the balance."""
        return self.__balance

    def deposit(self, amount):
        """Adds funds to the account if the amount is valid."""
        if amount > 0:
            self.__balance += amount
            return True, f"Successfully deposited ${amount:.2f}"
        return False, "Invalid deposit amount."

    def withdraw(self, amount):
        """Deducts funds if the balance is sufficient."""
        if amount <= 0:
            return False, "Invalid withdrawal amount."
        if amount > self.__balance:
            return False, "Insufficient funds available."

        self.__balance -= amount
        return True, f"Successfully withdrew ${amount:.2f}"


class BankDatabase:
    """Simulates the bank's central server holding customer accounts."""
    def __init__(self):
        # Initializing the database with dummy customer records
        self._accounts = {
            "1001": Account("1001", "1234", "Alice Smith", 5000.00),
            "1002": Account("1002", "5678", "Bob Jones", 1200.50),
            "1003": Account("1003", "9999", "Charlie Brown", 50.00)
        }

    def get_account(self, account_number):
        """Retrieves an account object if it exists."""
        return self._accounts.get(account_number, None)


class ATM:
    """Handles the physical hardware interaction and session state machine."""
    def __init__(self, bank_database):
        self.db = bank_database
        self.current_account = None  # Tracks who is currently logged in

    def start(self):
        """The main execution loop for the ATM hardware interface."""
        print("=== WELCOME TO APEX COOPERATIVE BANK ATM ===")
        acc_num = input("Please enter your Account Number: ").strip()
        account = self.db.get_account(acc_num)

        if not account:
            print("Error: Account record not found. Card returned.")
            return

        # PIN Validation Layer (Max 3 attempts simulation)
        attempts = 0
        while attempts < 3:
            pin = input("Enter your 4-digit PIN: ").strip()
            if account.verify_pin(pin):
                self.current_account = account
                print(f"\nWelcome back, {account.account_holder}!")
                self._show_menu()
                return
            else:
                attempts += 1
                print(f"Incorrect PIN. Attempts remaining: {3 - attempts}")

        print("\nCard confiscated due to excessive wrong attempts. Please contact your branch.")

    def _show_menu(self):
        """Internal system menu for authenticated users."""
        while True:
            print("\nATM options:")
            print("1. Check Balance")
            print("2. Deposit Funds")
            print("3. Withdraw Cash")
            print("4. Exit")

            choice = input("Select an option (1-4): ").strip()

            if choice == "1":
                print(f"Your Current Balance is: ${self.current_account.get_balance():.2f}")

            elif choice == "2":
                try:
                    amount = float(input("Enter deposit amount: $"))
                    success, message = self.current_account.deposit(amount)
                    print(message)
                except ValueError:
                    print("Error: Please enter a valid numerical value.")

            elif choice == "3":
                try:
                    amount = float(input("Enter withdrawal amount (Multiples of $20): $"))
                    success, message = self.current_account.withdraw(amount)
                    print(message)
                except ValueError:
                    print("Error: Please enter a valid numerical value.")

            elif choice == "4":
                print("\nThank you for banking with us. Please take your card! Goodbye.")
                self.current_account = None
                break
            else:
                print("Invalid configuration option selected. Please try again.")


# --- Execution Block ---
if __name__ == "__main__":
    # Create the central database
    central_db = BankDatabase()

    # Initialize the ATM machine with the central database access
    atm_machine = ATM(central_db)

    # Fire up the machine interface
    atm_machine.start()

"""Online Shopping Cart Product price calculation is hidden from users. The system automatically applies: Product price × quantity, Discount (if applicable). Final total calculation is hidden inside the system."""

class Shop:
    def __init__(self):
        self.__cart = []

    def addProd(self, items, price, quantity):
        self.__cart.append((items, price, quantity))

    def __calc_tot(self):
        total = 0
        for items, price, quantity in self.__cart:
            total += price*quantity
        return total

    def show_bill(self):
        for item, price, quantity in self.__cart:
            print(f'Your bought {quantity} number of {item} of price {price}')

        print(f'Total Bill: {self.__calc_tot()}')

c = Shop()
while True:
    item = input('Enter item you want to buy: ')
    price = float(input('Enter the price: '))
    qty = float(input('Enter quantity: '))

    c.addProd(item,price,qty)
    choice = input('Are you done?').lower().strip()
    if choice=='no':
        break

c.show_bill()

"""An online shopping platform allows customers to pay using different payment methods such as Credit Card and Bitcoin. Although all payment methods must
perform the common task of processing a payment.  the actual implementation differs: A Credit Card payment requires validating the card number and
charging the amount. A Bitcoin payment requires verifying the wallet address and transferring cryptocurrency. The checkout system should not need to know the internal details of each payment method. It should simply call a common method to process the payment. Implement this system using Data Abstraction in Python by creating an abstract
class PaymentMethod with an abstract method process_payment(). Then create concrete subclasses CreditCard and Bitcoin that provide their own
implementations.
"""

from abc import ABC, abstractmethod

class PaymentMethod(ABC):
    @abstractmethod
    def processPayment(self, amount):
        pass

class Database:
    def __init__(self):
        self._account = ['1001-102-101', '1001-102-102', '1001-102-103', '1001-102-104']
        self._bitid = ['A1B2C3D4F1', 'A1B2C3D4F2', 'A1B2C3D4F3', 'A1B2C3D4F4', 'A1B2C3D4F5']

class CreditCard(PaymentMethod):
    def __init__(self, acc, db):
        self.acc = acc
        self.db = db

    def processPayment(self, amount):
        print("Credit card payment...")
        if self.acc in self.db._account:
            print('Card validated')
            print(f'Processing payment of {amount} TK')
        else:
            print('Enter a valid account number')

class Bitcoin(PaymentMethod):
    def __init__(self, acc, db):
        self.acc = acc
        self.db = db

    def processPayment(self, amount):
        print("\nBitcoin payment...")
        if self.acc in self.db._bitid:
            print('Bitcoin ID validated')
            print(f'Processing payment of {amount} Bitcoin')
        else:
            print('Enter a valid Bitcoin ID')

db=Database()
c = CreditCard('1001-102-102', db)
b = Bitcoin('A1B2C3D4F3', db)

c.processPayment(10000)
b.processPayment(20)

"""12 Batch Lab Final Assessment (Robi)

Write a python program that creates a dictionary containing the names of employees as keys and their salaries as values. Then, perform the following operations:
  - Add new employee "Ratan" with salary of 75000 to the dictionary
  - Update the salary of an existing employee "Ali" to 85000
  - Remove an employee "Asfi" from the dictionary
  - Display the name and salary of each employee in the dictionary
"""

employee = {"Khalil":29000, "Rahim":30000, "Ali":50000, "Asfi":36000, "Poly":60000}
print('Original dictionary: ',employee)

#1
employee["Ratan"] = 75000
print(employee)

#2
employee["Ali"] = 85000
print(employee)

#3
del employee["Asfi"]
print(employee)

#4
for name, sal in employee.items():
    print(f'{name}: {sal}')

"""Create three classes: Sitar, Tabla, Dhol, each having a method called play(). Each class should define the play() method to print a message like "Strumming the sitar", "Playing the tabla" or "Beating the dhol". Create one object from each class and store them in a list. Iterate through the list and call the play() method on each object to demonstrate polymorphism in action."""

class Sitar:
    def play(self):
        print('Strumming the sitar')

class Tabla:
    def play(self):
        print('Playing the tabla')

class Dhol:
    def play(self):
        print('Beating the dhol')

s = Sitar()
t = Tabla()
d = Dhol()

obj = [s,t,d]
for o in obj:
    o.play()

"""Write a python function called format_and_filter names that takes a list of names in lowercase(strings) and returns a new list with the following modifications:
- Convert all names to proper case (capitalize the first letter of each name and make all other letters lowercase)
- Remove any names that contain the substring 'masud'
- Format the names in the order: last name, middle, first name
"""

def format_and_filter(names):
    form_name = [nam.strip().title() for nam in names]
    upd_name = [n for n in form_name if "masud" not in n.lower()]
    print('List of names without "masud": ',upd_name)

    for name in upd_name:
        part = name.split(maxsplit=2)
        while len(part)<3:
            part.append('')

        first, mid, last = part
        print(f'{last} {mid} {first}')

n = []
while True:
    ele = input('Enter name: ')
    n.append(ele)
    choice = input('Wish to continue? ')
    if choice.lower() == 'no':
        break

print(f'The original list of names: {n}')
format_and_filter(n)

"""Visualize student performance over semesters for the following data:
semesters = ['Sem1', 'Sem2', 'Sem3', 'Sem4', 'Sem5', 'Sem6']
total_marks = [550,600,350,450,360,370]
"""

sem = ['Sem1', 'Sem2', 'Sem3', 'Sem4', 'Sem5', 'Sem6']
total_marks = [550,600,350,450,360,370]

xlen = np.arange(len(sem))
plt.plot(xlen,total_marks, color='green', linestyle='-', marker='o')
plt.xlabel('Semesters')
plt.ylabel('Marks')
plt.title('Marks distribution across semesters')
plt.xticks(xlen, sem, rotation=35)
plt.show()

"""12 Batch lab Final Assessment (All material)

First create the dataframe from the dictionary given below and then perfomr the following operations: {
- 'book_id':[201,202,203,204,205]
  'title':['Python Basics','Data Science', 'Web Development', 'Machine Learning', 'Algorithms'],
  'author':['A. Smith', 'B. Johnson', 'C. Lee', 'D.Wilson', 'E. Brown'],
  'price':[29.99,39.99,34.99,49.99,44.99],
  'copies_sold':[120,85,65,110,95]
}

- Find the book with the highest price
- Calculate the average copies sold
- Add a new column 'revenue' (price*copies_sold)
- Find the author with the lowest selling book
- Add a new column 'discount': '10% off if price>40', '5% off if 30<=price<=40', 'No discount if price<30'
"""

library = {
    'book_id': [201,202,203,204,205],
    'title': ['Python Basics','Data Science', 'Web Development', 'Machine Learning', 'Algorithms'],
    'author': ['A. Smith', 'B. Johnson', 'C. Lee', 'D.Wilson', 'E. Brown'],
    'price': [29.99,39.99,34.99,49.99,44.99],
    'copies_sold': [120,85,65,110,95]
}
df = pd.DataFrame(library)
print(df)

#a
sort = df.sort_values('price', ascending=False)
highestPrice = sort.iloc[0][['book_id','title']]
print('Book with the highest price: ',highestPrice)

#b
avg = df['copies_sold'].mean()
print("Average copies sold: ",avg)

#c
df['revenue'] = df['price']*df['copies_sold']
print(df)

#d
sortBooks = df.sort_values('copies_sold',ascending=True)
lowestSell = sortBooks.iloc[0][['author','title']]
print('Lowest selling book author: ',lowestSell)

#e
discount = []
for p in df['price']:
    if p>40:
        discount.append(10)
    elif p<30:
        discount.append(0)
    else:
        discount.append(5)

df['discount_percentage'] = discount
print(df)

"""Make a class called Car. The __init__() method for Car should store two attributes: a make and a model. Make a method called describe_car() that prints these two information and a method called start_engine() that prints a message indicating the car's engine has started. Make an instance called my_car from your class. Print the two attributes individually and then call methods"""

class Car:
     def __init__(self,make,model):
          self.make = make
          self.model = model

     def describe_car(self):
          print('Car make: ',self.make)
          print('Car model: ',self.model)

     def start_engine(self):
          print("The car is started")

my_car = Car('Toyota','Prius')
print(my_car.make)
print(my_car.model)

my_car.describe_car()
my_car.start_engine()

"""Write a python function called extract_middle() that takes a list of integers and returns a new list containing the middle half of the elements. The function should return the third quartile integers of the list."""

def extract_middle(num):
    n = len(num)

    start = int(n*0.5)
    end = int(n*0.75)
    return num[start:end]

num = [10,10,24,13,28,28,20,12,15,24,18,19,30,21,25]
num = sorted(num)
print('The original number: ',num)
newlist = extract_middle(num)
print('The middle part of the number: ',newlist)

"""Python Theory exam

students = [
    {'id':1, 'name':'A', 'marks':78},
    {'id':2, 'name':'B', 'marks':91},
    {'id':3, 'name':'C', 'marks':67}
]
Develop a python program to classify students into the following grade categories: "A" (80 and above), "B" (70-79), "C" (60-69) and "Fail" (below 60). Store and present the classified result in a structured dictionary grouped by grade
"""

students = [
    {'id':1, 'name':'A', 'marks':78},
    {'id':2, 'name':'B', 'marks':91},
    {'id':3, 'name':'C', 'marks':67},
    {'id':4, 'name':'D', 'marks':50},
    {'id':5, 'name':'E', 'marks':75}
]

print(students)

group = {'A':[], 'B':[], 'C':[], 'F':[]}

for std in students:
    m = std['marks']
    if m >= 80:
        grade='A'
    elif m >= 70 and m<=79:
        grade='B'
    elif m >= 60 and m<=69:
        grade='C'
    else:
        grade='F'
    print(f'Student name: {std['name']} Marks: {std['marks']} Grade: {grade}')

    group[grade].append({
        'id':std['id'], 'name':std['name'], 'marks':m
    })

print("Result grouped by grade: ",group)

"""Create a python program that uses randint function from the random module to generate two lists of random integers, convert them into numpy arrays and reshape them into 3x4 matrices. Perform element wise addition, subtraction, multiplication between two arrays"""

import random
import numpy as np

list1 = np.random.randint(0,12,12)
list2 = np.random.randint(13,24,12)

arr1 = np.array(list1)
arr2 = np.array(list2)

arr1 = np.reshape(arr1, (3,4))
arr2 = np.reshape(arr2, (3,4))

print('Addition: \n',np.add(arr1,arr2))
print('Subtraction: \n',np.subtract(arr1,arr2))
print('Multiplication: \n',np.multiply(arr1,arr2))

"""You are given a list of integers representing daily temperatures. A peak is defined as a value that is strictly greater than its immediate neighbours. Your task is to I)Identify all the peaks in the list, II) Print the index and value of each peak, III) Print the total number of peaks"""

temps = [30,32,29,35,34,36,33,31,40,39]
l = len(temps)
index = []
for i in range(l-1):
    if i==0 and temps[i]>temps[i+1]:
        index.append(i)
    elif i==l-1 and temps[i]>temps[i-1]:
        index.append(i)
    elif temps[i]>temps[i+1] and temps[i]>temps[i-1]:
        index.append(i)

print('The peaks are at index: ',index)
for i in index:
    print(f'Peak found at index {i} with value {temps[i]}')

print('Total number of peaks: ',len(index))

"""Write a python program using the Pandas library to create a dataframe containing employee data with columns such as Employee name, Department, Salary and Years of Experience. Then display the dataframe, find the average salary of all employees and identify the employee with the highest salary"""

employee = {
    'Name': ['Maliha', 'Fariha', 'Tasnim', 'Samia', 'Muntaha'],
    'Department': ['IT', 'HR', 'Marketing', 'Marketing', 'IT'],
    'Salary': [30000,50000,20000,60000,85000],
    'Experience': [3,4,1,5,8]
    }
df = pd.DataFrame(employee)
print(df)

avg = df['Salary'].mean()
print("Average salary of all employees", avg)

top = df.sort_values('Salary', ascending=False)
highestEmp = top.iloc[0]
print('Employee with the highest salary: ',highestEmp)

"""Write a python program using the Matplotlib library to compare the performance of two students across six subjects (Math, Physics, Chemistry, Biology, English, ICT) using a line graph and use different line styles and markers for each student, add a legend and include a suitable title with labeled axes"""

subject = ['Math', 'Physics', 'Chemistry', 'Biology', 'English', 'ICT']
s1 = [70,96,58,69,79,88]
s2 = [96,58,69,80,68,70]

x = np.arange(len(subject))
plt.plot(x,s1,color='red',linestyle='-',marker='o',label='Student 1')
plt.plot(x,s2,color='green',linestyle='--',marker='s',label='Student 2')
plt.xlabel('Subjects')
plt.ylabel('Marks')
plt.xticks(x,subject,rotation=35)
plt.title('Student marks distribution')
plt.legend()
plt.show()

"""Design a library management system where define a base class LibraryItem and derive classes Book and CD from it. Include appropriate attributes and demonstrate method overriding where applicable. Create instances of the classes and implement a method to display all issued items in the system."""

class LibraryItem:
    def __init__(self, name, year, status):
        self.name = name
        self.year = year
        self.__status = status

    def borrow(self):
        print('The item is issued')

    def ret(self):
        print('The item is returned')

    def display(self):
        print('Name: ',self.name)
        print('Year: ',self.year)

    def get_status(self):
        return self.__status

    def set_status(self,status):
        self.__status = status

class Book(LibraryItem):
    def __init__(self,name,year,status,author):
        super().__init__(name,year,status)
        self.author = author

    def borrow(self):
        print('The book is issued')
        super().set_status('Issued')

    def ret(self):
        print('The book is returned')
        super().set_status('Available')

class CD(LibraryItem):
    def __init__(self,name,year,status,publisher):
        super().__init__(name,year,status)
        self.publisher = publisher

    def borrow(self):
        print('The CD is issued')
        super().set_status('Issued')

    def ret(self):
        print('The CD is returned')
        super().set_status('Available')

def displayIssue(obj):
    if obj.get_status() == 'Issued':
        obj.display()

b1 = Book('ABC',2008,'Issued','MNO')
b2 = Book('XYZ',1998,'Available','RO')
c1 = CD('JHK',2010,'Issued','KOL')
c2 = CD('MAF',2020,'Issued','OIP')

b1.ret()
b2.borrow()

for i in [b1,b2,c1,c2]:
    displayIssue(i)

"""Write a python program that demonstrates file handling and exception handling by asking the user to input a filename, attempting to open and read the file, displaying its contents if the file exists and handling errors such as file not found or invalid file access using appropriate exception handling techniques"""

filename = input('Enter a filename: ')
try:
    with open(filename, 'r') as file:
        data = file.read()
    print("Content: ",data)
except FileNotFoundError as f:
    print('Error: ',f)
except PermissionError as p:
    print('Error: ',p)
except Exception as e:
    print('Unexpected error: ',e)
else:
    print('Execution complete')